# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1258, 856)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setStyleSheet("background-color: rgb(17,17,17);\n"
"border-radius: 10px;\n"
"")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_2.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_superior = QtWidgets.QFrame(self.frame)
        self.frame_superior.setMinimumSize(QtCore.QSize(0, 45))
        self.frame_superior.setMaximumSize(QtCore.QSize(16777215, 50))
        self.frame_superior.setStyleSheet("QFrame{\n"
"background-color: rgb(17,17,17);\n"
"}\n"
"\n"
"QPushButton{\n"
"border-radius:18px;\n"
"background-color: rgb(17, 17, 17);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: rgb(44,44,44);\n"
"}")
        self.frame_superior.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_superior.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_superior.setObjectName("frame_superior")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_superior)
        self.horizontalLayout.setSpacing(15)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        spacerItem = QtWidgets.QSpacerItem(999, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.btn_minimizar = QtWidgets.QPushButton(self.frame_superior)
        self.btn_minimizar.setMinimumSize(QtCore.QSize(38, 38))
        self.btn_minimizar.setMaximumSize(QtCore.QSize(38, 38))
        self.btn_minimizar.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons/minus (2).svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_minimizar.setIcon(icon)
        self.btn_minimizar.setIconSize(QtCore.QSize(36, 36))
        self.btn_minimizar.setObjectName("btn_minimizar")
        self.horizontalLayout.addWidget(self.btn_minimizar)
        self.btn_maximizar = QtWidgets.QPushButton(self.frame_superior)
        self.btn_maximizar.setMinimumSize(QtCore.QSize(38, 38))
        self.btn_maximizar.setMaximumSize(QtCore.QSize(38, 38))
        self.btn_maximizar.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("icons/chevrons-up (1).svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_maximizar.setIcon(icon1)
        self.btn_maximizar.setIconSize(QtCore.QSize(36, 36))
        self.btn_maximizar.setObjectName("btn_maximizar")
        self.horizontalLayout.addWidget(self.btn_maximizar)
        self.btn_normal = QtWidgets.QPushButton(self.frame_superior)
        self.btn_normal.setMinimumSize(QtCore.QSize(38, 38))
        self.btn_normal.setMaximumSize(QtCore.QSize(38, 38))
        self.btn_normal.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("icons/chevrons-down (1).svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_normal.setIcon(icon2)
        self.btn_normal.setIconSize(QtCore.QSize(36, 36))
        self.btn_normal.setObjectName("btn_normal")
        self.horizontalLayout.addWidget(self.btn_normal)
        self.btn_cerrar = QtWidgets.QPushButton(self.frame_superior)
        self.btn_cerrar.setMinimumSize(QtCore.QSize(38, 38))
        self.btn_cerrar.setMaximumSize(QtCore.QSize(38, 38))
        self.btn_cerrar.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("icons/x (2).svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_cerrar.setIcon(icon3)
        self.btn_cerrar.setIconSize(QtCore.QSize(36, 36))
        self.btn_cerrar.setObjectName("btn_cerrar")
        self.horizontalLayout.addWidget(self.btn_cerrar)
        self.verticalLayout_2.addWidget(self.frame_superior)
        self.frame_contenido = QtWidgets.QFrame(self.frame)
        self.frame_contenido.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_contenido.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_contenido.setObjectName("frame_contenido")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_contenido)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(5)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame_3 = QtWidgets.QFrame(self.frame_contenido)
        self.frame_3.setMinimumSize(QtCore.QSize(310, 0))
        self.frame_3.setMaximumSize(QtCore.QSize(310, 16777215))
        self.frame_3.setStyleSheet("background-color: rgb(44,44,44);\n"
"border-radius:20px;")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_10.setContentsMargins(-1, 40, -1, 40)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label = QtWidgets.QLabel(self.frame_3)
        self.label.setStyleSheet("color:rgb(218,0,55);\n"
"font:87 12pt \"Arial Black\";")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout_5.addWidget(self.label)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.comboBox_puerto = QtWidgets.QComboBox(self.frame_3)
        self.comboBox_puerto.setMinimumSize(QtCore.QSize(150, 30))
        self.comboBox_puerto.setMaximumSize(QtCore.QSize(170, 30))
        self.comboBox_puerto.setStyleSheet("QComboBox{\n"
"border:3px solid #111111;\n"
"border-radius: 5px;\n"
"min-width: 6em;\n"
"color:rgb(218,0,55);\n"
"font: 87 10pt \"Arial Black\";\n"
"}\n"
"\n"
"QComboBox::drop-down{\n"
"subcontrol-origin:padding;\n"
"subcontrol-position: top right;\n"
"width: 15px;\n"
"border-left-width: 3px;\n"
"border-left-color:#111111;\n"
"border-left-style:solid;\n"
"border-top-right-radius: 4px;\n"
"border-bottom-right-radius: 4px;\n"
"}\n"
"\n"
"QComboBox QAbstractItemView{\n"
"background:#2c2c2c;\n"
"selection-background-color:#ff0037;\n"
"color:rgb(218,0,55);\n"
"}")
        self.comboBox_puerto.setObjectName("comboBox_puerto")
        self.horizontalLayout_3.addWidget(self.comboBox_puerto)
        self.btn_actualizar = QtWidgets.QPushButton(self.frame_3)
        self.btn_actualizar.setMinimumSize(QtCore.QSize(38, 38))
        self.btn_actualizar.setMaximumSize(QtCore.QSize(38, 38))
        self.btn_actualizar.setStyleSheet("QPushButton{\n"
"border-radius:18px;\n"
"background-color: rgb(44,44,44);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: rgb(17, 17, 17);\n"
"}")
        self.btn_actualizar.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("icons/rotate-cw.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_actualizar.setIcon(icon4)
        self.btn_actualizar.setIconSize(QtCore.QSize(30, 30))
        self.btn_actualizar.setObjectName("btn_actualizar")
        self.horizontalLayout_3.addWidget(self.btn_actualizar)
        self.verticalLayout_5.addLayout(self.horizontalLayout_3)
        self.verticalLayout_8.addLayout(self.verticalLayout_5)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_8.addItem(spacerItem1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem2)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_2 = QtWidgets.QLabel(self.frame_3)
        self.label_2.setStyleSheet("color:rgb(218,0,55);\n"
"font:87 12pt \"Arial Black\";")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_6.addWidget(self.label_2)
        self.comboBox_velocidad = QtWidgets.QComboBox(self.frame_3)
        self.comboBox_velocidad.setMinimumSize(QtCore.QSize(150, 30))
        self.comboBox_velocidad.setMaximumSize(QtCore.QSize(170, 30))
        self.comboBox_velocidad.setStyleSheet("QComboBox{\n"
"border:3px solid #111111;\n"
"border-radius: 5px;\n"
"min-width: 6em;\n"
"color:rgb(218,0,55);\n"
"font: 87 10pt \"Arial Black\";\n"
"}\n"
"\n"
"QComboBox::drop-down{\n"
"subcontrol-origin:padding;\n"
"subcontrol-position: top right;\n"
"width: 15px;\n"
"border-left-width: 3px;\n"
"border-left-color:#111111;\n"
"border-left-style:solid;\n"
"border-top-right-radius: 4px;\n"
"border-bottom-right-radius: 4px;\n"
"}\n"
"\n"
"QComboBox QAbstractItemView{\n"
"background:#2c2c2c;\n"
"selection-background-color:#ff0037;\n"
"color:rgb(218,0,55);\n"
"}")
        self.comboBox_velocidad.setObjectName("comboBox_velocidad")
        self.verticalLayout_6.addWidget(self.comboBox_velocidad)
        self.horizontalLayout_4.addLayout(self.verticalLayout_6)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem3)
        self.verticalLayout_8.addLayout(self.horizontalLayout_4)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_8.addItem(spacerItem4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem5)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setSpacing(15)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.btn_conectar = QtWidgets.QPushButton(self.frame_3)
        self.btn_conectar.setMinimumSize(QtCore.QSize(170, 40))
        self.btn_conectar.setMaximumSize(QtCore.QSize(170, 40))
        self.btn_conectar.setStyleSheet("QPushButton{\n"
"background-color: rgb(208,0,55);\n"
"font:87 12pt \"Arial Black\";\n"
"color:rgb(17,17,17);\n"
"border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: rgb(17,17,17);\n"
"font:87 12pt \"Arial Black\";\n"
"color:rgb(218,0,55);\n"
"border-radius: 10px;\n"
"}\n"
"")
        self.btn_conectar.setObjectName("btn_conectar")
        self.verticalLayout_7.addWidget(self.btn_conectar)
        self.btn_desconectar = QtWidgets.QPushButton(self.frame_3)
        self.btn_desconectar.setMinimumSize(QtCore.QSize(170, 40))
        self.btn_desconectar.setMaximumSize(QtCore.QSize(170, 40))
        self.btn_desconectar.setStyleSheet("QPushButton{\n"
"background-color: rgb(208,0,55);\n"
"font:87 12pt \"Arial Black\";\n"
"color:rgb(17,17,17);\n"
"border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: rgb(17,17,17);\n"
"font:87 12pt \"Arial Black\";\n"
"color:rgb(218,0,55);\n"
"border-radius: 10px;\n"
"}\n"
"")
        self.btn_desconectar.setObjectName("btn_desconectar")
        self.verticalLayout_7.addWidget(self.btn_desconectar)
        self.horizontalLayout_5.addLayout(self.verticalLayout_7)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem6)
        self.verticalLayout_8.addLayout(self.horizontalLayout_5)
        self.verticalLayout_10.addLayout(self.verticalLayout_8)
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_9.addItem(spacerItem7)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem8)
        self.label_3 = QtWidgets.QLabel(self.frame_3)
        self.label_3.setMinimumSize(QtCore.QSize(150, 150))
        self.label_3.setMaximumSize(QtCore.QSize(150, 150))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("icons/escudo_negativo.png"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_6.addWidget(self.label_3)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem9)
        self.verticalLayout_9.addLayout(self.horizontalLayout_6)
        self.verticalLayout_10.addLayout(self.verticalLayout_9)
        self.horizontalLayout_2.addWidget(self.frame_3)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame_2 = QtWidgets.QFrame(self.frame_contenido)
        self.frame_2.setStyleSheet("background-color: rgb(44,44,44);\n"
"border-radius:20px;")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.frame_5 = QtWidgets.QFrame(self.frame_2)
        self.frame_5.setMinimumSize(QtCore.QSize(200, 0))
        self.frame_5.setMaximumSize(QtCore.QSize(200, 16777215))
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.frame_5)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        spacerItem10 = QtWidgets.QSpacerItem(20, 102, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_13.addItem(spacerItem10)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.label_4 = QtWidgets.QLabel(self.frame_5)
        self.label_4.setStyleSheet("color:rgb(218,0,55);\n"
"font:87 10pt \"Arial Black\";")
        self.label_4.setObjectName("label_4")
        self.verticalLayout_11.addWidget(self.label_4)
        self.label_5 = QtWidgets.QLabel(self.frame_5)
        self.label_5.setStyleSheet("color:rgb(218,0,55);\n"
"font:87 10pt \"Arial Black\";")
        self.label_5.setObjectName("label_5")
        self.verticalLayout_11.addWidget(self.label_5)
        self.label_6 = QtWidgets.QLabel(self.frame_5)
        self.label_6.setStyleSheet("color:rgb(218,0,55);\n"
"font:87 10pt \"Arial Black\";")
        self.label_6.setObjectName("label_6")
        self.verticalLayout_11.addWidget(self.label_6)
        self.label_7 = QtWidgets.QLabel(self.frame_5)
        self.label_7.setStyleSheet("color:rgb(218,0,55);\n"
"font:87 10pt \"Arial Black\";")
        self.label_7.setObjectName("label_7")
        self.verticalLayout_11.addWidget(self.label_7)
        self.horizontalLayout_8.addLayout(self.verticalLayout_11)
        self.verticalLayout_12 = QtWidgets.QVBoxLayout()
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.val_actual1 = QtWidgets.QLabel(self.frame_5)
        self.val_actual1.setStyleSheet("color:rgb(218,0,55);\n"
"font:87 10pt \"Arial Black\";")
        self.val_actual1.setObjectName("val_actual1")
        self.verticalLayout_12.addWidget(self.val_actual1)
        self.val_max1 = QtWidgets.QLabel(self.frame_5)
        self.val_max1.setStyleSheet("color:rgb(218,0,55);\n"
"font:87 10pt \"Arial Black\";")
        self.val_max1.setObjectName("val_max1")
        self.verticalLayout_12.addWidget(self.val_max1)
        self.val_min1 = QtWidgets.QLabel(self.frame_5)
        self.val_min1.setStyleSheet("color:rgb(218,0,55);\n"
"font:87 10pt \"Arial Black\";")
        self.val_min1.setObjectName("val_min1")
        self.verticalLayout_12.addWidget(self.val_min1)
        self.val_prom1 = QtWidgets.QLabel(self.frame_5)
        self.val_prom1.setStyleSheet("color:rgb(218,0,55);\n"
"font:87 10pt \"Arial Black\";")
        self.val_prom1.setObjectName("val_prom1")
        self.verticalLayout_12.addWidget(self.val_prom1)
        self.horizontalLayout_8.addLayout(self.verticalLayout_12)
        self.verticalLayout_13.addLayout(self.horizontalLayout_8)
        spacerItem11 = QtWidgets.QSpacerItem(20, 102, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_13.addItem(spacerItem11)
        self.horizontalLayout_7.addWidget(self.frame_5)
        self.frame_6 = QtWidgets.QFrame(self.frame_2)
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.frame_6)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.graph_grafica1 = QtWidgets.QHBoxLayout()
        self.graph_grafica1.setObjectName("graph_grafica1")
        self.horizontalLayout_10.addLayout(self.graph_grafica1)
        self.horizontalLayout_7.addWidget(self.frame_6)
        self.verticalLayout_3.addWidget(self.frame_2)
        self.frame_4 = QtWidgets.QFrame(self.frame_contenido)
        self.frame_4.setStyleSheet("background-color: rgb(44,44,44);\n"
"border-radius:20px;")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self.frame_4)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.frame_7 = QtWidgets.QFrame(self.frame_4)
        self.frame_7.setMinimumSize(QtCore.QSize(200, 0))
        self.frame_7.setMaximumSize(QtCore.QSize(200, 16777215))
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.frame_7)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        spacerItem12 = QtWidgets.QSpacerItem(20, 102, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_14.addItem(spacerItem12)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout()
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.label_12 = QtWidgets.QLabel(self.frame_7)
        self.label_12.setStyleSheet("color:rgb(218,0,55);\n"
"font:87 10pt \"Arial Black\";")
        self.label_12.setObjectName("label_12")
        self.verticalLayout_15.addWidget(self.label_12)
        self.label_13 = QtWidgets.QLabel(self.frame_7)
        self.label_13.setStyleSheet("color:rgb(218,0,55);\n"
"font:87 10pt \"Arial Black\";")
        self.label_13.setObjectName("label_13")
        self.verticalLayout_15.addWidget(self.label_13)
        self.label_14 = QtWidgets.QLabel(self.frame_7)
        self.label_14.setStyleSheet("color:rgb(218,0,55);\n"
"font:87 10pt \"Arial Black\";")
        self.label_14.setObjectName("label_14")
        self.verticalLayout_15.addWidget(self.label_14)
        self.label_15 = QtWidgets.QLabel(self.frame_7)
        self.label_15.setStyleSheet("color:rgb(218,0,55);\n"
"font:87 10pt \"Arial Black\";")
        self.label_15.setObjectName("label_15")
        self.verticalLayout_15.addWidget(self.label_15)
        self.horizontalLayout_11.addLayout(self.verticalLayout_15)
        self.verticalLayout_16 = QtWidgets.QVBoxLayout()
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.val_actual2 = QtWidgets.QLabel(self.frame_7)
        self.val_actual2.setStyleSheet("color:rgb(218,0,55);\n"
"font:87 10pt \"Arial Black\";")
        self.val_actual2.setObjectName("val_actual2")
        self.verticalLayout_16.addWidget(self.val_actual2)
        self.val_max2 = QtWidgets.QLabel(self.frame_7)
        self.val_max2.setStyleSheet("color:rgb(218,0,55);\n"
"font:87 10pt \"Arial Black\";")
        self.val_max2.setObjectName("val_max2")
        self.verticalLayout_16.addWidget(self.val_max2)
        self.val_min2 = QtWidgets.QLabel(self.frame_7)
        self.val_min2.setStyleSheet("color:rgb(218,0,55);\n"
"font:87 10pt \"Arial Black\";")
        self.val_min2.setObjectName("val_min2")
        self.verticalLayout_16.addWidget(self.val_min2)
        self.val_prom2 = QtWidgets.QLabel(self.frame_7)
        self.val_prom2.setStyleSheet("color:rgb(218,0,55);\n"
"font:87 10pt \"Arial Black\";")
        self.val_prom2.setObjectName("val_prom2")
        self.verticalLayout_16.addWidget(self.val_prom2)
        self.horizontalLayout_11.addLayout(self.verticalLayout_16)
        self.verticalLayout_14.addLayout(self.horizontalLayout_11)
        spacerItem13 = QtWidgets.QSpacerItem(20, 102, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_14.addItem(spacerItem13)
        self.horizontalLayout_14.addWidget(self.frame_7)
        self.frame_8 = QtWidgets.QFrame(self.frame_4)
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.frame_8)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.graph_grafica2 = QtWidgets.QHBoxLayout()
        self.graph_grafica2.setObjectName("graph_grafica2")
        self.horizontalLayout_12.addLayout(self.graph_grafica2)
        self.horizontalLayout_14.addWidget(self.frame_8)
        self.verticalLayout_3.addWidget(self.frame_4)
        self.verticalLayout_3.setStretch(0, 1)
        self.verticalLayout_3.setStretch(1, 1)
        self.horizontalLayout_2.addLayout(self.verticalLayout_3)
        self.horizontalLayout_2.setStretch(0, 1)
        self.horizontalLayout_2.setStretch(1, 3)
        self.verticalLayout_4.addLayout(self.horizontalLayout_2)
        self.verticalLayout_2.addWidget(self.frame_contenido)
        self.verticalLayout.addWidget(self.frame)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Puerto Serial"))
        self.label_2.setText(_translate("MainWindow", "Velocidad"))
        self.btn_conectar.setText(_translate("MainWindow", "Conectar"))
        self.btn_desconectar.setText(_translate("MainWindow", "Desconectar"))
        self.label_4.setText(_translate("MainWindow", "Valor Actual"))
        self.label_5.setText(_translate("MainWindow", "Valor Maximo"))
        self.label_6.setText(_translate("MainWindow", "Valor Minimo"))
        self.label_7.setText(_translate("MainWindow", "Promedio"))
        self.val_actual1.setText(_translate("MainWindow", "50"))
        self.val_max1.setText(_translate("MainWindow", "50"))
        self.val_min1.setText(_translate("MainWindow", "50"))
        self.val_prom1.setText(_translate("MainWindow", "50"))
        self.label_12.setText(_translate("MainWindow", "Valor Actual"))
        self.label_13.setText(_translate("MainWindow", "Valor Maximo"))
        self.label_14.setText(_translate("MainWindow", "Valor Minimo"))
        self.label_15.setText(_translate("MainWindow", "Promedio"))
        self.val_actual2.setText(_translate("MainWindow", "50"))
        self.val_max2.setText(_translate("MainWindow", "50"))
        self.val_min2.setText(_translate("MainWindow", "50"))
        self.val_prom2.setText(_translate("MainWindow", "50"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
